services:
  db:
    image: postgres:16-alpine
    container_name: brevly-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: brevly
    volumes:
      - brevly_pg_data:/var/lib/postgresql/data

volumes:
  brevly_pg_data:
